apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stressor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stressor
  template:
    metadata:
      labels:
        app: cpu-stressor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodeType
                operator: In
                values:
                - "autoscaling"
      tolerations:
      - key: "oci.oraclecloud.com/oke-is-preemptible"
        operator: "Exists"
        effect: "NoSchedule"      
      containers:
        - name: cpu-stressor
          #image: narmidm/k8s-pod-cpu-stressor:latest
          image: ocir.us-ashburn-1.oci.oraclecloud.com/idfiw4nvpzwl/k8s-pod-cpu-stressor:latest
          args:
            - "-cpu=0.5"
            - "-duration=60s"
            - "-forever"
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
