apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodeType
                operator: In
                values:
                - "autoscaling"
      tolerations:
      - key: "oci.oraclecloud.com/oke-is-preemptible"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
  selector:
    run: php-apache
  
--- 

apiVersion: v1
kind: Service
metadata:
  name: php-apache-internal-lb
  labels:
    run: php-apache
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci-network-load-balancer.oraclecloud.com/internal: "true"
    oci-network-load-balancer.oraclecloud.com/subnet: "ocid1.subnet.oc1.iad.aaaaaaaaxxmx4ybbmpvmn5vrx5uhh24gqkwt2lfpjwkoahd5c6en5kaaribq"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    run: php-apache
